import Head from 'next/head'
import { FC } from 'react'
import { NavBar } from '../NavBar'
import styles from './MainLayout.module.css'



export const MainLayout: FC = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className={styles.main}>
        { children }
      </main>
    </div>
  )
}
